Lab03/Lab03/Models/Partido.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Lab03.Models
{
    public class Partido
    {
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Numero de Partido es Requerido")]
        public int NoPartido { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "La Fecha del Partido es Requerida")]
        public DateTime FechaPartido { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "El Nombre del Grupo es Requerido")]
        public string Grupo { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "El Nombre del Pais es Requerido")]
        public string Pais1 { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "El Nombre del Pais es Requerido")]
        public string Pais2 { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "El Nombre del Estadio es Requerido")]
        public string Estadio { get; set; }

        public Partido(int NoPartido, DateTime FechaPartido, string Grupo, string Pais1, string Pais2, string Estadio)
        {
            this.NoPartido = NoPartido;
            this.FechaPartido = FechaPartido;
            this.Grupo = Grupo;
            this.Pais1 = Pais1;
            this.Pais2 = Pais2;
            this.Estadio = Estadio;
        }

        public Comparison<Partido> CompareByNoPartido = delegate (Partido i, Partido j)
        {
            return i.NoPartido.CompareTo(j.NoPartido);
        };

        public Comparison<Partido> CompareByFechaPartido = delegate (Partido i, Partido j)
        {
            return i.FechaPartido.CompareTo(j.NoPartido);
        };

        public Comparison<Partido> CompareByPais1 = delegate (Partido i, Partido j)
        {
            return i.Pais1.CompareTo(j.Pais1);
        };

        public Comparison<Partido> CompareByPais2 = delegate (Partido i, Partido j)
        {
            return i.Pais2.CompareTo(j.Pais2);
        };

        public Comparison<Partido> CompareByEstadio = delegate (Partido i, Partido j)
        {
            return i.Estadio.CompareTo(j.Estadio);
        };

        public Comparison<Partido> CompareByGroup = delegate (Partido i, Partido j)
        {
            return i.Grupo.CompareTo(j.Grupo);
        };

        public override string ToString()
        {
            return $"{NoPartido}|{FechaPartido}|{Grupo}|{Pais1}|{Pais2}|{Estadio}";
        }

        public bool Equals(Partido partido)
        {
            bool igual = partido.NoPartido == NoPartido;
            igual = igual && partido.FechaPartido == FechaPartido;
            igual = igual && partido.Grupo == Grupo;
            igual = igual && partido.Pais1 == Pais1;
            igual = igual && partido.Pais2 == Pais2;
            igual = igual && partido.Estadio == Estadio;
            return igual;
        }

    }
}

Lab03/Lab03/Controllers/PartidoController.cs
using Lab03.Classes.Models;
using Lab03.Models;
using Libreria_de_Clases;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lab03.Controllers
{
    public class PartidoController : Controller
    {

        //Se crea un Jugador Momentaneo para pasar los datos (Carga del archivo)
        List<Partido> ListadePartidos = new List<Partido>();

        public static int contador = 0;
        public void imprimirArchivo()
        {
           
          StreamWriter escritor = new StreamWriter(@"C:\Users\Bitacora.txt");
        
          foreach (var linea in DataBase.Instance.ArchivoTexto)
          {
                    escritor.WriteLine(linea);
          }
          escritor.Close();
            if(contador == 0)
            {
                TempData["msg"] = "<script> alert('El Archivo de Texto se ha Guardado en C:Users');</script>";
            }
            contador++;

        }

        // GET: Partido
        public ActionResult Index()
        {
            try
            {
                return View(DataBase.Instance.ArbolPartido.Orders("InOrder"));
            }
            catch
            {
                return View();
            }
        }

        // GET: Partido/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ArbolBinario/Create
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                Partido nuevopartido = new Partido(Convert.ToInt32(collection["NoPartido"]), Convert.ToDateTime(collection["FechaPartido"]), collection["Grupo"], 
                    collection["Pais1"], collection["Pais2"], collection["Estadio"]);

                DataBase.Instance.ArchivoTexto.Add("INSERCION");
                DataBase.Instance.ArchivoTexto.Add("\tPartido Numero: " + Convert.ToInt32(collection["NoPartido"]));
                DataBase.Instance.ArchivoTexto.Add("\tFecha del Partido: " + Convert.ToDateTime(collection["FechaPartido"]));
                DataBase.Instance.ArchivoTexto.Add("\tGrupo: " + collection["Grupo"]);
                DataBase.Instance.ArchivoTexto.Add("\tPais 1: " + collection["Pais1"]);
                DataBase.Instance.ArchivoTexto.Add("\tPais 2: " + collection["Pais2"]);
                DataBase.Instance.ArchivoTexto.Add("\tEstadio: " + collection["Estadio"]);
                DataBase.Instance.ArchivoTexto.Add("");

                imprimirArchivo();

                DataBase.Instance.ArbolPartido.Insertar(nuevopartido);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Partido/Editar/5
        public ActionResult Edit(int? id)
        {
            return View();
        }

        // POST: Partido/Editar/5
        [HttpPost]
        public ActionResult Edit(int? id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Partido/Delete/5
        public ActionResult Delete(int? id)
        {
            return View();
        }

        // POST: Partido/Delete/5
        [HttpPost]
        public ActionResult Delete(int? id, int NoPartido, DateTime FechaPartido, string Grupo , string Pais1, string Pais2, string Estadio)
        {
            try
            {
                Partido nuevopartido = new Partido(NoPartido,FechaPartido,Grupo,Pais1,Pais2,Estadio);

                DataBase.Instance.ArbolPartido.Eliminar(nuevopartido, ref DataBase.Instance.ArbolPartido.Raiz);

                DataBase.Instance.ArchivoTexto.Add("ELIMINACION");
                DataBase.Instance.ArchivoTexto.Add("\tPartido Numero: " + NoPartido);
                DataBase.Instance.ArchivoTexto.Add("\tFecha del Partido: " + FechaPartido);
                DataBase.Instance.ArchivoTexto.Add("\tGrupo: " + Grupo);
                DataBase.Instance.ArchivoTexto.Add("\tPais 1: " + Pais1);
                DataBase.Instance.ArchivoTexto.Add("\tPais 2: " + Pais2);
                DataBase.Instance.ArchivoTexto.Add("\tEstadio: " + Estadio);
                DataBase.Instance.ArchivoTexto.Add("");

                imprimirArchivo();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult UploadFile()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        //Aca se hace el Ingreso por medio de Archivo de Texto, ya que el Boton de Result esta Linkeado.
        public ActionResult UploadFile(HttpPostedFileBase file, int? Tipo)
        {
            if (Path.GetExtension(file.FileName) != ".json")
            {
                //Aca se debe de Agregar una Vista de Error, o de Datos No Cargados
                TempData["msg"] = "<script> alert('Error El Archivo Cargado No es de Tipo Json');</script>";
                return RedirectToAction("Error", "Shared");
            }

            Stream Direccion = file.InputStream;
            //Se lee el Archivo que se subio, por medio del Lector

            StreamReader Lector = new StreamReader(Direccion);
            //El Archivo se lee en una linea para luego ingresarlo

            string Dato = "";
            Dato = Lector.ReadLine();

            while (Dato != null)
            {
                Dato = Lector.ReadLine();
                Dato = Lector.ReadLine();

                string Linea = "{";

                for (int i = 0; i < 6; i++)
                {
                    Linea = Linea + Dato;
                    Dato = Lector.ReadLine();
                }

                Linea = Linea + "}";

                Partido objTemporal = JsonConvert.DeserializeObject<Partido>(Linea);
                ListadePartidos.Add(objTemporal);

                Linea = "";
            }

            try
            {
                if (Tipo == 1)
                {
                    foreach (var item in ListadePartidos)
                    {
                        if (item.Estadio != null)
                        {
                            item.codigoPK = 1;

                            DataBase.Instance.ArchivoTexto.Add("INSERCION POR NUMERO DE PARTIDO");
                            DataBase.Instance.ArchivoTexto.Add("\tPartido Numero: " + item.noPartido);
                            DataBase.Instance.ArchivoTexto.Add("\tFecha del Partido: " + item.FechaPartido);
                            DataBase.Instance.ArchivoTexto.Add("\tGrupo: " + item.Grupo);
                            DataBase.Instance.ArchivoTexto.Add("\tPais 1: " + item.Pais1);
                            DataBase.Instance.ArchivoTexto.Add("\tPais 2: " + item.Pais2);
                            DataBase.Instance.ArchivoTexto.Add("\tEstadio: " + item.Estadio);
                            DataBase.Instance.ArchivoTexto.Add("");

                            imprimirArchivo();

                            DataBase.Instance.ArbolPartido.Insertar(item);
                        }
                    }
                }
                else if (Tipo == 2)
                {
                    foreach (var item in ListadePartidos)
                    {
                        if (item.Estadio != null)
                        {
                            item.codigoPK = 2;

                            DataBase.Instance.ArchivoTexto.Add("INSERCION POR FECHA DEL PARTIDO");
                            DataBase.Instance.ArchivoTexto.Add("\tPartido Numero: " + item.noPartido);
                            DataBase.Instance.ArchivoTexto.Add("\tFecha del Partido: " + item.FechaPartido);
                            DataBase.Instance.ArchivoTexto.Add("\tGrupo: " + item.Grupo);
                            DataBase.Instance.ArchivoTexto.Add("\tPais 1: " + item.Pais1);
                            DataBase.Instance.ArchivoTexto.Add("\tPais 2: " + item.Pais2);
                            DataBase.Instance.ArchivoTexto.Add("\tEstadio: " + item.Estadio);
                            DataBase.Instance.ArchivoTexto.Add("");

                            imprimirArchivo();

                            DataBase.Instance.ArbolPartido.Insertar(item);
                        }
                    }
                }
                return RedirectToAction("Index");
            }
            catch
            {
                TempData["msg"] = "<script> alert('Error Los Datos del Archivo Json no se pudieron Insertar, Comprueba que ejecutaste Visual Studio en Modo Administrador');</script>";
                return RedirectToAction("Index");
            }  

        }

        public ActionResult Busqueda(string Tipo, string Search)
        {
            if (Tipo == "No Partido" && Search != null)
            {

                List<Partido> ListaDeBuscados = new List<Partido>();
                List<Partido> NoPartidoBuscado = new List<Partido>();
                NoPartidoBuscado.Clear();
                ListaDeBuscados.Clear();
                ListaDeBuscados = DataBase.Instance.ArbolPartido.ObtenerArbol();

                try
                {
                    foreach (var item in ListaDeBuscados)
                    {
                        if (item.noPartido == Convert.ToInt32(Search))
                        {
                            NoPartidoBuscado.Add(item);
                        }

                    }
                    if(NoPartidoBuscado.Count == 0)
                    {

Lab03/Lab03/Views/Partido/Busqueda.cshtml
@model Lab03.Models.Partido

<h2><font color="#FFFFFF">Busqueda</font></h2>


<body background="~/Content/Estadio.jpg">
</body>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div id="contenedor"></div>
        <h4><font color="#FFFFFF">Seleccione una Opcion para Buscar</font></h4>
        <form method="get" action="@Url.Action("Busqueda", "Partido")">
            <label for="search"><font color="#FFFFFF">Buscar Por:</font></label>
            <select name="Tipo" id="Tipo">
                <option value="No Partido">No. de Partido</option>
                <option value="Fecha de Partido">Fecha de Partido</option>
            </select>
            <input type="text" name="Search" id="Search" />
            <button type="submit">Buscar</button>
        </form>
    </div>

}

@Html.Raw(TempData["msg1"])



<div>
    @Html.ActionLink("Listado de Partidos", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Lab03/Lab03/Views/Partido/Create.cshtml
@model Lab03.Models.Partido

@{
    ViewBag.Title = "Agregar Partido";
}

<body background="~/Content/EstadioRusia.jpg"></body>

<h1>Agregar Partido</h1>
<br />

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4 Align="right">@Html.ActionLink("Back to List", "Index")</h4>
        <h4>Datos del encuentro</h4>

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Número de Partido", htmlAttributes: new { @class = "control-label col-md-2" })
            @*@Html.LabelFor(model => model.noPartido, htmlAttributes: new { @class = "control-label col-md-2" })*@
        <div class="col-md-10">
                @Html.EditorFor(model => model.noPartido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.noPartido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Fecha del Partido", htmlAttributes: new { @class = "control-label col-md-2" })
            @*Html.LabelFor(model => model.FechaPartido, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaPartido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaPartido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Grupo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Grupo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Grupo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Pais1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pais1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pais1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Pais2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pais2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pais2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estadio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Estadio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Estadio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

Lab03/Lab03/Views/Partido/Delete.cshtml
@model Lab03.Models.Partido

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Estas Seguro que Deseas Eliminar Este Partido?</h3>
<div>
    <hr />
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Ver Lista de Partidos", "Index")
        </div>
    }
</div>

Lab03/Lab03/Views/Partido/Index.cshtml
@model IEnumerable<Lab03.Models.Partido>

@{
    ViewBag.Title = "Partidos";
}

<body background="~/Content/FondoGris.jpg">
</body>

<h1>Listado de Partidos</h1>

<p>
    @Html.ActionLink("Crear Nuevo", "Create")|
    @Html.ActionLink("Buscar", "Busqueda")
</p>

@Html.Raw(TempData["msg"])

<br />

<table class="table">
    <tr>
        <th>
            <h4 align="center">@Html.DisplayName("Número de Partido")</h4>
            @*@Html.DisplayNameFor(model => model.noPartido)*@
        </th>
        <th>
            <h4 align="center">@Html.DisplayName("Fecha del Partido")</h4>
            @*@Html.DisplayNameFor(model => model.FechaPartido)*@
        </th>
        <th>
            <h4 align="center">@Html.DisplayNameFor(model => model.Grupo)</h4>
        </th>
        <th>
            <h4 align="center">@Html.DisplayNameFor(model => model.Pais1)</h4>
        </th>
        <th>
            <h4 align="center">@Html.DisplayNameFor(model => model.Pais2)</h4>
        </th>
        <th>
            <h4 align="center">@Html.DisplayNameFor(model => model.Estadio)</h4>
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td align="center">
                @Html.DisplayFor(modelItem => item.noPartido)
            </td>
            <td align="center">
                @Html.DisplayFor(modelItem => item.FechaPartido)
            </td>
            <td align="center">
                @Html.DisplayFor(modelItem => item.Grupo)
            </td>
            <td align="center">
                @Html.DisplayFor(modelItem => item.Pais1)
            </td>
            <td align="center">
                @Html.DisplayFor(modelItem => item.Pais2)
            </td>
            <td align="center">
                @Html.DisplayFor(modelItem => item.Estadio)
            </td>
            <td align="center">
                @Html.ActionLink("Delete", "Delete", new { NoPartido = item.noPartido, FechaPartido = item.FechaPartido, Grupo = item.Grupo, Pais1 = item.Pais1, Pais2 = item.Pais2, Estadio = item.Estadio })
            </td>
        </tr>
    }

</table>

Lab03/Lab03/Views/Partido/UploadFile.cshtml
@{
    ViewBag.Title = "Cargar Archivo";
}

<body background="~/Content/River.jpg">
</body>

<h1><font color="#FFFFFF">Subir Archivo</font></h1>

<br />

@using (Html.BeginForm("UploadFile", "Partido", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken();
    @Html.ValidationSummary();

    <br />
    <div class="row">
        <div class="col-md-12">
            <h2 align="center"><font color="#FFFFFF">Agregar con Archivo</font></h2>

            <br />

            <div class="col-md-12" align="center" id="contenedor">
                <h4><font color="#FFFFFF">Seleccione la Primary Key del Árbol</font></h4>
                <form method="get" action="@Url.Action("Index", "Partido")">
                    <label for="Cambiar"><font color="#FFFFFF">Agregar Por:</font></label>
                    <select name="Tipo" id="Tipo">
                        <option value="1">Número de Partido</option>
                        <option value="2">Fecha del Partido</option>
                    </select>
                </form>
            </div>

            <br />

            <h4 align="center">
                <font color="#FFFFFF">Para agregar un grupo de personas a través de un archivo .json</font>
            </h4>

            <div align="center" class="form-group">
                <input type="file" name="file" value="Examinar" class="btn-default" style="color:transparent" />
            </div>
            <div align="center" class="form-group">
                <button type="submit" class="btn btn-default">Subir archivo</button>
            </div>

        </div>
    </div>
}